version: '3.9'
services:
  backened:
    build: .
    volumes:
      - .:/flask
    ports:
      - 8001:5000
    image: app:flask
    container_name: flask_container
    command: python main.py
    depends_on:
      - db

#   build:
 #     context: .
  ## command: 'python -u consumer.py'
    #depends_on:
     # - db

  db:
    image: mysql:latest
    container_name: flaskdb_container
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306


networks:
  default:
    external: true
    name: mynetwork